docker:
  releases:
  - latest
  latest:
    version: 1.2.0
    url: https://github.com/dotcloud/docker/archive/v1.2.0.tar.gz
    sha256: d7ab9ab0984044efdeba6b292e2e8b07f1f14fef51a444f8a3749d30d32567da
    md5: cea0b533c0fae5d2aaef6b3abd92af5d
